### ISSUE TITLE
Can this work with JS?

### ISSUE THREAD

**Issue by xiki808** [rodydavis/flutter_hybrid_template#1]
Thanks a lot for your post and code! This is exactly what I am looking for. I am very new to flutter but I want to check if it's possible to port the web project I am building with Lit. 

I have hosted my web project locally on a home server and I am pointing the bundle to the URL path of where the bundle is on that server.  My workstation and android device are all on the same network and I can see the web component from both when I browse for my project. I changed the name to the name of my main web component element. I have also changed the source in web_component.dart body html to `<${widget.name}></${widget.name}>` and kept the script calling the bundle as is. Not sure if there are issues with crossorigin - it's hard to test and debug.

Should I expect that this works with a Lit project written in JS? I am getting a blank screen ( only the blue title at the top - I removed the button )

**Comment by xiki808** [comment]
It has something to do with my host :( ... 

I hosted your JS file (main.js) on my server and app does not load the web component. I think it has something to do with cross origin setting, but I don't know what to do with it.

**Comment by xiki808** [comment]
I figured it. Android doesn't allow for accessing external resources over http but only over https. After setting my local env behind https I could call my JS file hosted there.

**Comment by rodydavis** [comment]
Oh that’s great to know! Thanks for the follow up!
